services:
  rivus-master:
    build: .
    image: rivus:dev

  rivus-streaming:
    build: .
    image: rivus:dev

  rivus-snapshot:
    build: .
    image: rivus:dev

  rivus-maintenance:
    build: .
    image: rivus:dev
