#!/bin/sh
set -eu

MYSQL_ROOT_SECRET="${MYSQL_ROOT_PASS:-${MYSQL_ROOT_PASSWORD:-}}"
: "${MYSQL_ROOT_SECRET:?MYSQL_ROOT_PASS or MYSQL_ROOT_PASSWORD is required}"
: "${RIVUS_META_MYSQL_USER:?RIVUS_META_MYSQL_USER is required}"
: "${RIVUS_META_MYSQL_PASSWORD:?RIVUS_META_MYSQL_PASSWORD is required}"
: "${RIVUS_META_MYSQL_DATABASE:?RIVUS_META_MYSQL_DATABASE is required}"

META_MYSQL_HOST="${META_MYSQL_HOST:-meta-mysql}"

until MYSQL_PWD="$MYSQL_ROOT_SECRET" mysql -h "$META_MYSQL_HOST" -uroot -Nse "SELECT 1" >/dev/null 2>&1; do
  sleep 2
done

MYSQL_PWD="$MYSQL_ROOT_SECRET" mysql -h "$META_MYSQL_HOST" -uroot <<SQL
CREATE DATABASE IF NOT EXISTS \`${RIVUS_META_MYSQL_DATABASE}\`;
CREATE USER IF NOT EXISTS '${RIVUS_META_MYSQL_USER}'@'%' IDENTIFIED BY '${RIVUS_META_MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${RIVUS_META_MYSQL_DATABASE}\`.* TO '${RIVUS_META_MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
SQL
